### ISSUE TITLE
Changelog link validation failing for PRs

### ISSUE THREAD

**Issue by isvargasmsft** [microsoftgraph/changelog-link-check#15]
Changelog link validation is failing for PRs but there is not an apparent reason for the failure. 

Here the list of affected PRs:
https://github.com/microsoftgraph/microsoft-graph-docs/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3A%22invalid+links%22

**Comment by jasonjoh** [comment]
It appears that the failures are on new topics in the PR. Currently the validation is simply checking the URL's validity, and since these aren't live yet, they're failing. I'll need to add additional logic to check for new topics in the PR.
